### ISSUE TITLE
Watermark PDFs with customer data

### ISSUE THREAD

**Issue by sepi2048** [notrab/nextjs-commercejs-example#2]
Hi,
I found your YouTube playlist, [Create a Next.js store with Commerce.js](https://www.youtube.com/playlist?list=PLs2PzMqLzi7VRJoFcBXMabDue2uC6_eJX) - very helpful! 

I would like to take this further by adding a watermark to a PDF uploaded as a digital product. Currently there is no build-in way to do this using commerce.js, so I was wondering if you have any thoughts on where and how in the checkout process (somewhere after the purchase and before the download link is created) the PDF could be marked with the order number and customers full name?

**Comment by notrab** [comment]
I'd recommend you reach out to the Commerce.js team to ask on how they'd do this. https://slack.commercejs.com is a good place to start 😄
