### ISSUE TITLE
Error serializing `.products` on categories/[slug].js

### ISSUE THREAD

**Issue by Dupflo** [notrab/nextjs-commercejs-example#3]
<img width="964" alt="Capture d’écran 2021-08-05 à 00 17 38" src="https://user-images.githubusercontent.com/39828779/128290144-7c1c2d18-a3ba-4d03-8d98-69b0e512e75d.png">

**Comment by notrab** [comment]
Hey

You are no doubt using a newer version of the API since this example was created.

Can you try updating the code to use an array for the slug?

For example:

```js
const { data: products } = await commerce.products.list({
    category_slug: [slug],
  });
```
